### ISSUE TITLE
[Frontend] Auth-UI

### ISSUE THREAD

**Issue by Risa2422** [Cornerstone-CICCC/nodejs-final-project-terra_formars#1]
## Overview
Initial setup for the frontend auth UI

## Tasks
- [x]  Create Home page
- [x]  Create Sign / Login modal
- [x]  Create Create room 
- [x]   Set login / signup validation
