### ISSUE TITLE
[Frontend] Implement join room function

### ISSUE THREAD

**Issue by Risa2422** [Cornerstone-CICCC/nodejs-final-project-terra_formars#13]

**Comment by Risa2422** [comment]
## Overview
Implement room UI

## Tasks
- [ ]  Send socket once move to a pending room
- [ ]  Send post api once move to a pending room
- [ ]  Display player list in live 
- [ ]  Send socket when "I'm ready to play" button
- [ ] Once every one is ready, move to a play room
