### ISSUE TITLE
[Backend] Initial project setup

### ISSUE THREAD

**Issue by benono** [Cornerstone-CICCC/nodejs-final-project-terra_formars#2]
## Overview
Initial setup for the backend project

## Tasks
- [x] Project initialization
  - [x] Create package.json
  - [x] TypeScript configuration
  - [x] ESLint & Prettier setup
- [x] Express.js setup
  - [x] Install required packages
    - express
    - cors
    - dotenv
    - typescript
    - ts-node
    - @types/express
  - [x] Basic server configuration
  - [x] Environment variables setup
- [x] MongoDB setup
  - [x] Install mongoose
  - [x] Database connection configuration
  - [x] Connection test
- [x] Create project structure
  ```
  backend/
  ├── src/
  │   ├── config/
  │   ├── models/
  │   ├── routes/
  │   ├── controllers/
  │   ├── middleware/
  │   └── server.ts
  ├── .env
  ├── .gitignore
  └── package.json
  ```

Labels: backend, enhancement
Milestone: Sprint 1
