### ISSUE TITLE
[Backend] Implement authentication routes

### ISSUE THREAD

**Issue by benono** [Cornerstone-CICCC/nodejs-final-project-terra_formars#3]
## Overview
Implement user authentication system

## Tasks
- [ ] Install required packages
  - [x] bcryptjs (password hashing)
  - [x] jsonwebtoken (JWT authentication)
  - [ ] express-validator (input validation)
- [x] Create User model
  ```typescript
  interface IUser {
    password: string;
    name: string;
    createdAt: Date;
  }
  ```
- [x] Implement auth routes
  - [x] POST /api/auth/signup
  - [x] POST /api/auth/login
  - [x] GET /api/auth/me
- [x] Implement JWT middleware
- [ ] Implement validations
  - [ ] Password strength validation
- [ ] Error handling

## Test items
- [ ] User registration
- [ ] Login authentication
- [ ] JWT token verification

Labels: backend, enhancement
Milestone: Sprint 1
