### ISSUE TITLE
[frontend] styling

### ISSUE THREAD

**Issue by Risa2422** [Cornerstone-CICCC/nodejs-final-project-terra_formars#40]
## Todo

- [x] Only the Drawer can draw.
- [x] For responsive views, display the chat as a toast notification.
- [x] Display the Codeword in the list.
- [ ] Add a scroll animation to the "Please wait for everyone to get ready." message.
- [x] Add animation when the modal is displayed.
- [x] Add animation when each button is clicked.
- [x] Display 'Correct!' briefly and wait a few seconds before transitioning to the result screen in the final round.
