### ISSUE TITLE
[Backend] Implement Pending Room Management api/socket.io

### ISSUE THREAD

**Issue by benono** [Cornerstone-CICCC/nodejs-final-project-terra_formars#6]
Title: [Backend] Implement Pending Room Management api/socket.io

## Overview

Create API endpoints and socket.io events for pending room management functionality with codeword access

## Tasks

- [x] Create Room model

  ```typescript
  interface IRoom {
    codeword: string; // codeword (unique) for joining
    status: "pending" | "active" | "finished";
    hostId: string; // room host
    members: {
      // member management
      userId: string;
      isReady: boolean;
      joinedAt: Date;
    }[];
    settings: {
      maxPlayers: number;
      numberOfPrompts: number; // number of rounds
      timeLimit: number; // drawing time limit (seconds)
    };
    currentRound: number;
    theme?: string; // current theme
  }
  ```

- [x] Implement room routes

  - [x] POST /api/rooms
    - Request: { codeword, maxPlayers, numberOfPrompts, timeLimit }
    - Creates private room with settings
  - [x] POST /api/rooms/join
    - Request: { codeword }
    - Validates codeword and joins room if valid
  - [x] POST /api/rooms/:id/ready
    - Marks user as ready
    - Triggers game start when all ready
  - [x] DELETE /api/rooms/:id
    - Host only: Cancels room

- [x] Add validations

  - [x] Codeword uniqueness
  - [x] Player limit check
  - [x] Host privileges
  - [x] Ready status management

- [x] Add error handling

- [x] Add socket.io

  - [x] room:join
  - [x] room:leave
  - [x] room:ready
  - [x] room:start

- [x] Add tests
  - [x] What if host leaves?
  - [x] What if all members leave?

Labels: backend, enhancement
