### ISSUE TITLE
[Frontend] Room-UI

### ISSUE THREAD

**Issue by Risa2422** [Cornerstone-CICCC/nodejs-final-project-terra_formars#8]
## Overview
Implement room UI

## Tasks
- [x]  Create Pending room
- [x]  Create Play room (drawer)
- [x]  Create Play room
